- flink-examples/src/main/scala/io/pravega/examples/flink/util/PravegaParameters.scala
Closes #34 
Updated only the default URI since the code has already got parameterized option to accept other values
```
$ bin/run-example.sh [--controller <URI>] [--scope <name>] [--stream <name>]
[--startTime <long>] [--output <path>]
```
> Issue 34 Changed default pravega controller URI to use localhost

- flink-examples/src/main/scala/io/pravega/examples/flink/iot/TurbineHeatProcessor.scala
Changed the name of the flink job. This job name gets emitted in metrics raw and causes data not to appear in statsd. This is probably a flink bug but we want to be compatible with the current flink release.
Added name for pravega source.
> Changed the name of the flink job

- build.gradle
Removes a repository listed in the `repositories` section of `build.gradle` that is no longer needed.
Fixes #54
> Issue 54: Remove unnecessary repository 

- .gitignore
- anomaly-detection/src/main/java/io/pravega/anomalydetection/event/pipeline/AbstractPipeline.java
- anomaly-detection/src/main/java/io/pravega/anomalydetection/event/pipeline/PipelineRunner.java
- anomaly-detection/src/main/java/io/pravega/anomalydetection/event/pipeline/PravegaAnomalyDetectionProcessor.java
- anomaly-detection/src/main/java/io/pravega/anomalydetection/event/pipeline/PravegaEventPublisher.java
- anomaly-detection/src/main/java/io/pravega/anomalydetection/event/pipeline/StreamCreator.java
- flink-examples/doc/flink-wordcount/README.md
- flink-examples/src/main/java/io/pravega/examples/flink/Utils.java
- flink-examples/src/main/java/io/pravega/examples/flink/iot/TurbineHeatProcessor.java
- flink-examples/src/main/java/io/pravega/examples/flink/wordcount/Constants.java
- flink-examples/src/main/java/io/pravega/examples/flink/wordcount/WordCountReader.java
- flink-examples/src/main/java/io/pravega/examples/flink/wordcount/WordCountWriter.java
- flink-examples/src/main/scala/io/pravega/examples/flink/iot/TurbineHeatProcessorScala.scala
**Change Log**
- Added `Utils` class to create streams as needed
- Updates to use builder syntax
- Remove explicit scale policy from word count, anomaly detection samples
**How to Test**
- Manual testing in Flink cluster
> [Issue-76] update samples to new builder API

- hadoop-examples/README.md
- hadoop-examples/build.gradle
- hadoop-examples/gradle.properties
- hadoop-examples/src/main/java/io/pravega/examples/hadoop/ExampleDriver.java
- hadoop-examples/src/main/java/io/pravega/examples/hadoop/PravegaOutputFormat.java
- hadoop-examples/src/main/java/io/pravega/examples/hadoop/PravegaOutputRecordWriter.java
- hadoop-examples/src/main/java/io/pravega/examples/hadoop/RandomTextWriter.java
- hadoop-examples/src/main/java/io/pravega/examples/hadoop/RandomWriter.java
- hadoop-examples/src/main/java/io/pravega/examples/hadoop/TextSerializer.java
- hadoop-examples/src/main/java/io/pravega/examples/hadoop/WordCount.java
- hadoop-examples/src/main/java/io/pravega/examples/hadoop/WordMean.java
- hadoop-examples/src/main/java/io/pravega/examples/hadoop/WordMedian.java
- hadoop-examples/src/main/java/io/pravega/examples/spark/WordCount.java
Signed-off-by: Bo Yang <b.yang@emc.com>
This PR adds a number of examples that exercise the Pravega Input Format implementation in the hadoop connectors project.
The files below are copied from apache hadoop and modfied a little bit to support Pravega
hadoop-examples/src/main/java/io/pravega/examples/hadoop/ExampleDriver.java
hadoop-examples/src/main/java/io/pravega/examples/hadoop/RandomTextWriter.java
hadoop-examples/src/main/java/io/pravega/examples/hadoop/RandomWriter.java
hadoop-examples/src/main/java/io/pravega/examples/hadoop/WordCount.java
hadoop-examples/src/main/java/io/pravega/examples/hadoop/WordMean.java
hadoop-examples/src/main/java/io/pravega/examples/hadoop/WordMedian.java
> [issue 75] hadoop-connectors examples

- flink-examples/README.md
- flink-examples/build.gradle
- flink-examples/doc/exactly-once/README.md
- flink-examples/src/main/java/io/pravega/examples/flink/primer/datatype/Constants.java
- flink-examples/src/main/java/io/pravega/examples/flink/primer/datatype/IntegerEvent.java
- flink-examples/src/main/java/io/pravega/examples/flink/primer/process/ExactlyOnceChecker.java
- flink-examples/src/main/java/io/pravega/examples/flink/primer/process/ExactlyOnceWriter.java
- flink-examples/src/main/java/io/pravega/examples/flink/primer/source/ThrottledIntegerEventProducer.java
- flink-examples/src/main/java/io/pravega/examples/flink/primer/util/FailingMapper.java
- This PR adds a Flink example job to demonstrate Pravega EXACTLY_ONCE feature. 
- Updated to use the builder API.
Fixes #72 
Flink job to demo Pravega EXACTLY_ONCE feature
See details in [README](https://github.com/pravega/pravega-samples/tree/flink-issue-72-take2/flink-examples/doc/exactly-once)
> [issue 72] Flink example - exactly once

- scenarios/turbine-heat-sensor/src/main/java/io/pravega/turbineheatsensor/TurbineHeatSensor.java
Fix in `TrubineHeatSensor.java` for avoiding the application to throw `NullPointerException`. Note that this PR only targets this specific problem (i.e., other exceptions or problems will be treated separately).
Fixes #85.
The reader (`SensorReader`) is incorrectly interacting with `produceStats` instead of with `consumeStats`. Moreover, the read loop of this class parses read events without checking for null events (e.g., after timeout). The fix consists of replacing reader interactions from `produceStats` to `consumeStats` as well as to check for a null read event before executing the parse logic.
Execute the application and verify that it does not throws NPE.
> Issue 85: turbineSensor throws occasional NPE

- README.md
Changed all absolute links by relative links in main README.md.
Fixes #108.
Removes absolute paths from links to enable relative redirection within the repository itself.
README links should be working and pointing to the current branch contents.
> Issue 108: Relative documentation links

- build.gradle
- flink-connector-examples/README.md
- gradle.properties
- pravega-client-examples/README.md
This PR deletes the `upload` instructions from `flink-connector-examples` README, as well as the associated tasks/properties in the main `build.gradle` file and `gradle.properties` file, respectively. 
Fixes #116.
Delete unnecessary README steps and build tasks to simplify the instructions for end-users.
Clone the PR changes and execute `gradlew installDist`. All the sample applications should be working as before this change.
> Issue 116: Deleted upload instructions in Flink connector samples

- scenarios/turbine-heat-sensor/src/main/java/io/pravega/turbineheatsensor/TurbineHeatSensor.java
Minor fix in `TurbineHeatSensor.java` regarding the use of client factories while creating writers. Note that this PR specifically targets to avoid `java.lang.RuntimeException: ManagedChannel allocation site` exception to be thrown (e.g., the app may throw other exceptions that will be addressed separately).  
Fixes #84.
The constructor of `TemperatureSensors` receives by parameter a client factory to create event writers. However, it was creating writers via a global static client factory, which was in turn shared to create readers as well. Creating readers/writers carelessly, jointly with the fact that resources are not correctly closed, could be the cause for the closing channel exception to be thrown. In this …
> Issue 84: Channel not shutdown correctly in TurbineHeatSensor sample

- gradle.properties
- hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/wordcount/PravegaOutputFormat.java
Removed `DEFAULT_TXN_SCALE_GRACE_PERIOD_MS` constant and `transactionTimeoutScaleGracePeriod` call from `PravegaOutputFormat.java`. Moreover, this PR also updates the `hadoopConnectorVersion` version in `gradle.properties` to the last available artifact in version `0.3.0` so this fix can be tested.
Fixes #123.
Removes operations involving `scaleGracePeriod` in Hadoop wordcount sample that prevented gradle build to succeed.
Clone this PR and execute `./gradlew installDist`, it should be working. Also, execute the Hadoop wordcount example; it should be working as it was before this fix.
> Issue 123: Removed scaleGracePeriod from Hadoop wordcount sample

- gradle.properties
Changed the `develop` branch `gradle.properties` artifacts of Pravega and Hadoop/Flink connectors to version `0.4.0`.
Fixes #130.
Upgrade the version of project dependency artifacts.
Clone the `develop` branch and execute `./gradlew installDist`, the build should be downloading the new dependencies and passing.
> Issue 130: Updated artifacts version to 0.4.0.

- gradle.properties
Updated `gradle.properties` of r0.3 to set `samplesVersion=0.3.2-SNAPSHOT`. 
Fixes #143.
Upgrade `samplesVersion` in `gradle.properties`.
> Issue 143: Update samplesVersion to 0.3.2-SNAPSHOT.

- gradle.properties
Upgraded artifacts to version `0.3.2`.
Fixes #153.
Updates artifact versions in `gradle.properties` to `0.3.2`.
> Issue 153: Upgrade artifacts version to 0.3.2

- flink-connector-examples/src/main/java/io/pravega/example/flink/streamcuts/process/StreamBookmarker.java
- gradle.properties
Modify Flink StreamCuts sample to use the new `generateStreamCuts` call.
Fixes #160.
Replaces old code to get a new `StreamCut` after a given position by the new API call `generateStreamCuts`. This PR required the update of FlinkConnector with a Pravega version containing PR https://github.com/pravega/pravega/pull/2980.
The app should be working as before.
> Issue 160: Use new StreamCuts API call to get the end of a Stream slice

- gradle.properties
Updated samplesVersion to 0.5.0-SNAPSHOT.
Fixes #170.
Sets `samplesVersion` to 0.5.0-SNAPSHOT in `gradle.properties`.
> Issue 170: Updated samplesVersion to 0.5.0-SNAPSHOT

- flink-connector-examples/build.gradle
- flink-connector-examples/src/main/java/io/pravega/example/flink/streamcuts/process/StreamBookmarker.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/streamcuts/serialization/GuavaImmutableMapSerializer.java
- flink-connector-examples/src/main/resources/log4j.properties
- gradle.properties
- hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/PravegaFixedSegmentsOutputFormat.java
- hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/PravegaTeraSortOutputFormat.java
- hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/terasort/TeraGen.java
- hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/terasort/TeraSort.java
- hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/terasort/TeraStreamValidate.java
- hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/wordcount/WordCount.java
- scenarios/anomaly-detection/build.gradle
- scenarios/pravega-flink-connector-sql-samples/build.gradle
- scenarios/turbine-heat-processor/build.gradle
- scenarios/turbine-heat-processor/src/main/java/io/pravega/turbineheatprocessor/TurbineHeatProcessor.java
- scenarios/turbine-heat-processor/src/main/scala/io/pravega/turbineheatprocessor/TurbineHeatProcessorScala.scala
* Fixed guava library serialization issue
* updated flink version to 1.7.2
* updated pravega and Connector version to r0.5
To address https://github.com/pravega/pravega-samples/issues/197
Updated samples to use Pravega and Connector artifacts from `r0.5` and fixed issues specific to Flink serialization with respect to the guava library.
Run `./gradlew clean installDist`  and test samples using the instructions from readme docs
> [issue-197] Update samples to use r0.5 artifacts

- gradle.properties
Changed the `dev` branch `gradle.properties` artifacts of Pravega and Hadoop/Flink connectors to version latest available 0.6 artifacts. Changed samples version to `0.6.0-SNAPSHOT`.
Fixes #212.
Upgrade the version of project dependency artifacts.
Clone the `dev` branch and execute `./gradlew installDist`, the build should be downloading the new dependencies and passing.
> Issue 212: Updated artifact versions

- flink-connector-examples/build.gradle
- scenarios/anomaly-detection/build.gradle
- scenarios/pravega-flink-connector-sql-samples/build.gradle
- scenarios/turbine-heat-processor/build.gradle
Removes the Pravega client from Flink build dependencies.
Fixes #233.
According to @crazyzhou, 
>This bug is caused by the relocation of the io.grpc package. The return structure of the getClientInterceptor in flink connector is changed to io.pravega.shaded.io.grpc rather than io.grpc, causing the io.grpc return method not exist. See:
https://github.com/pravega/flink-connectors/blob/master/build.gradle#L157
It's a behaviour from the first commit of the repository. It was meant to shade the common libraries which could cause potential version conflicts with Flink.
My suggestion is to delete the pravega client dependency in the samples. See:
https://github.com/pravega/pravega-samples/blob/master/flink-connector-examp …
> Issue 233: Fix Flink samples build

- pravega-client-examples/src/main/java/io/pravega/example/consolerw/ConsoleWriter.java
Signed-off-by: Guangfeng Xu <Guangfeng.Xu@dell.com>
The help text in  `ConsoleWriter` says that we should use `WRITE_EVENT_RK <<{routingKey}>> , {event}` to write the `{event}` out to the Stream or the current Transaction using `{routingKey}`. However, according to the code, the correct operation should be `WRITE_EVENT_RK ({routingKey}) {event}`. Change the help text to match the code.
Fixes #253
Update the help text of ConsoleWriter.
Follow the `README.md` and the program should work.
> [issue-253] The help text and the code don't match

- gradle.properties
- schema-registry-examples/build.gradle
Updated all artifact versions to 0.8.0 and Flink version to the latest one. Updated Schema Registry version to 0.1.0 and dependency name.
Fixes #263 and #261.
Updates all artifact versions to 0.8.0 in `gradle.properties` with the exception of Schema Registry, which is in version 0.1.0. Also, fixed the dependency name of Schema Registry artifact. Flink version was updated to the last one (`1.10.2`).
`./gradlew clean installDist` should pass
> Issue 263: Prepare for 0.8 release

- flink-connector-examples/src/main/java/io/pravega/example/flink/primer/process/ExactlyOnceChecker.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/primer/process/ExactlyOnceWriter.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/streamcuts/process/StreamBookmarker.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/watermark/EventTimeAverage.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/wordcount/WordCountReader.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/wordcount/WordCountWriter.java
- scenarios/anomaly-detection/src/main/java/io/pravega/anomalydetection/event/pipeline/PravegaAnomalyDetectionProcessor.java
- scenarios/anomaly-detection/src/main/java/io/pravega/anomalydetection/event/pipeline/PravegaEventPublisher.java
- scenarios/turbine-heat-processor/src/main/java/io/pravega/turbineheatprocessor/TurbineHeatProcessor.java
- scenarios/turbine-heat-processor/src/main/scala/io/pravega/turbineheatprocessor/TurbineHeatProcessorScala.scala
Update serialization classes in Flink samples.
Fixes #272 
Replaces the following deprecated occurrences for serialization in Flink samples:
- `PravegaSerialization.deserializationFor` -> `new PravegaDeserializationSchema<>(xxx.class, new JavaSerializer<>())`
- `PravegaSerialization.serializationFor` -> `new PravegaSerializationSchema<>(new JavaSerializer<>())`
Flink samples build and work with this change.
> [issue-272] Remove the usage of PravegaSerialization

- flink-connector-examples/build.gradle
- gradle.properties
- scenarios/anomaly-detection/build.gradle
- scenarios/pravega-flink-connector-sql-samples/build.gradle
- scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/AbstractHandler.java
- scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/MaxTravellersPerDestination.java
- scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/PopularDestinationQuery.java
- scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/PopularTaxiVendor.java
- scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/PrepareMain.java
- scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/common/TripRecord.java
- scenarios/turbine-heat-processor/build.gradle
Signed-off-by: Brian Zhou <b.zhou@dell.com>
**Changes:**
This PR makes the following changes:
- Upgrade Flink connector to `0.9.0-50.e9d5a98-SNAPSHOT`
- Upgrade to Flink `1.11.2`
- Add `flink-clients_2.12` dependency to all Flink samples because it is required, mentioned in Flink 1.11 release notes [here](https://ci.apache.org/projects/flink/flink-docs-stable/release-notes/flink-1.11.html#reversed-dependency-from-flink-streaming-java-to-flink-client-flink-15090)
- Update the SQL sample to remove deprecate usages including
- Use DDL to create table to connect with Pravega stream, this uses the new Table API
- Use string to store json format timestamp, which is recommended in [official doc](https://ci.apache.org/projects/flink/flink-docs-release-1.11/dev/table/connectors/formats/json.html#da …
> [issue-273] Upgrade to Flink 1.11 and update the Flink SQL sample

- gradle.properties
- schema-registry-examples/build.gradle
- schema-registry-examples/src/main/java/io/pravega/schemaregistry/samples/codec/CompressionDemo.java
Updated all artifact versions to 0.9.0. Updated Schema Registry version to 0.2.0, added Pravega client dependency and fixed one API call signature.
Fixes #276.
Updates all artifact versions to 0.9.0 in `gradle.properties` with the exception of Schema Registry, which is in version 0.2.0. Also, added the Pravega client dependency in Schema Registry and fixed one API call signature in a sample.
`./gradlew clean installDist` should pass
Signed-off-by: Raúl <raul.gracia@emc.com>
> Issue 276: Prepare for 0.9 release

- spark-connector-examples/src/main/python/batch_file_to_pravega.py
- spark-connector-examples/src/main/python/batch_pravega_to_console.py
- spark-connector-examples/src/main/python/stream_bounded_pravega_to_console.py
- spark-connector-examples/src/main/python/stream_generated_data_to_pravega.py
- spark-connector-examples/src/main/python/stream_pravega_to_console.py
- spark-connector-examples/src/main/python/stream_pravega_to_pravega.py
- spark-connector-examples/src/main/scala/io/pravega/example/spark/StreamPravegaToConsole.scala
- spark-connector-examples/src/main/scala/io/pravega/example/spark/StreamPravegaToPravega.scala
These changes allow the Spark Scala examples to run on SDP. The examples continue to work on Pravega OSS.
> Issue 283: Update Spark examples to be compatible with SDP

- flink-connector-examples/doc/flink-wordcount/README.md
- flink-connector-examples/src/main/java/io/pravega/example/flink/primer/process/ExactlyOnceChecker.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/primer/source/ThrottledIntegerEventProducer.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/primer/util/FailingMapper.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/streamcuts/process/StreamBookmarker.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/watermark/EventTimeAverage.java
- flink-connector-examples/src/main/java/io/pravega/example/flink/wordcount/WordCountReader.java
- gradle.properties
- hadoop-connector-examples/build.gradle
- scenarios/anomaly-detection/src/main/java/io/pravega/anomalydetection/event/pipeline/PravegaAnomalyDetectionProcessor.java
- scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/AbstractHandler.java
- scenarios/turbine-heat-processor/src/main/dist/bin/run-example
- scenarios/turbine-heat-processor/src/main/java/io/pravega/turbineheatprocessor/TurbineHeatProcessor.java
- scenarios/turbine-heat-processor/src/main/scala/io/pravega/turbineheatprocessor/TurbineHeatProcessorScala.scala
- scenarios/turbine-heat-sensor/src/main/java/io/pravega/turbineheatsensor/TurbineHeatSensor.java
This PR has upgraded the Flink version to 1.12 and updated some deprecated/removed usage including
- [FLINK-6258](https://issues.apache.org/jira/browse/FLINK-6258) `ListCheckpointed`
- [FLINK-17074](https://issues.apache.org/jira/browse/FLINK-17074) `keyBy` with a string and number parameter
- [FLINK-19317](https://issues.apache.org/jira/browse/FLINK-19317) Make `EventTime` the default `TimeCharacteristic` + `timeWindow`
- [FLINK-17661](https://issues.apache.org/jira/browse/FLINK-17661) Deprecate old Watermark Assigner API
- [FLINK-19035](https://issues.apache.org/jira/browse/FLINK-19035) `DataStream#fold()`
Flink Exactly once app checker result:
```
// exactly once
============== Checker starts ===============
No duplicate found. EXACTLY_ONCE!
============== Checker ends  =============== …
```
> [issue-288] Update Flink samples to Flink 1.12 and fix deprecated

- build.gradle
- gradle.properties
* Updates Pravega dependency to 0.10.0 snapshot build
* Adds Pravega GPR as maven repository to pull Pravega snapshot builds from
* Removes any references of jcenter() as it is no longer available
Fixes #290.
.`/gradlew clean installDist` should pass
Signed-off-by: Igor Medvedev <medvedevigorek@gmail.com>
> Issue 290: Update Pravega to 0.10.0 snapshot build

- build.gradle
- gradle.properties
Signed-off-by: zhongle.wang <zhongle_wang@dell.com>
Changes the destination for snapshot artifacts from JCenter to GitHub Packages Registry.
Fixes #293 
- Snapshot repositories is updated to pull from GPR
- Removes jcenter()/jfrog references from build scripts
Once the PR is merged the next build on dev branch should pull the latest flink-connectors from the updated GPR.
**Known Limitations**
- Using snapshot packages in other repository is not allowed without the authentication.
Limitation can be handled in the following way:
- Create import token in pravega repository with read:packages scope. This can be shared with others
- In the other repository add the following to repositories list
``` …
```
> [Issue-293] Update dev branch to use flink-connectors 0.10.0 snapshot builds

- pravega-client-examples/src/main/java/io/pravega/example/consolerw/ConsoleReader.java
- pravega-client-examples/src/main/java/io/pravega/example/consolerw/ConsoleWriter.java
- pravega-client-examples/src/main/java/io/pravega/example/gettingstarted/HelloWorldReader.java
- pravega-client-examples/src/main/java/io/pravega/example/gettingstarted/HelloWorldWriter.java
- pravega-client-examples/src/main/java/io/pravega/example/secure/SecureBatchReader.java
- pravega-client-examples/src/main/java/io/pravega/example/secure/SecureReader.java
- pravega-client-examples/src/main/java/io/pravega/example/secure/SecureWriter.java
- pravega-client-examples/src/main/java/io/pravega/example/streamcuts/StreamCutsExample.java
- scenarios/turbine-heat-processor/README.md
- scenarios/turbine-heat-processor/src/main/java/io/pravega/turbineheatprocessor/TurbineHeatProcessor.java
- scenarios/turbine-heat-processor/src/main/scala/io/pravega/turbineheatprocessor/TurbineHeatProcessorScala.scala
- scenarios/turbine-heat-sensor/src/main/java/io/pravega/turbineheatsensor/TurbineHeatSensor.java
Signed-off-by: thekingofcity <3353040+thekingofcity@users.noreply.github.com>
The existing JavaSerializer used in the writer and reader of several examples is slow and vulnerable. Use UTF8StringSerializer instead.
Fixes #309 
Change JavaSerializer to UTF8StringSerializer in the following examples:
* scenarios\turbineheatsensor
* scenarios\turbineheatprocessor
* pravega-client-examples\gettingstarted
* pravega-client-examples\streamcuts
* pravega-client-examples\consolerw
* pravega-client-examples\secure
All examples should behave as before.
> [Issue-309] Use UTF8StringSerializer instead of JavaSerializer for better performance

- gradle.properties
Updated samples version to 0.11.0 and all dependency artifact versions to 0.11.0. Updated Schema Registry version to 0.4.0.
Fixes https://github.com/pravega/pravega-samples/issues/325.
Updated samples version to 0.11.0 and all dependency artifact versions to 0.11.0. Updated Schema Registry version to 0.4.0.
`./gradlew clean installDist` should pass
> Issue 325: Prepare for release 0.11

- gradle.properties
- scenarios/pravega-flink-connector-sql-samples/build.gradle
Updated samples version to 0.13.0 and all dependency artifact versions to 0.13.0. Updated Schema Registry version to 0.6.0. Changed to Flink Table Planner library in Flink SQL sample.
Fixes https://github.com/pravega/pravega-samples/issues/343.
Updated samples version to 0.13.0 and all dependency artifact versions to 0.13.0. Updated Schema Registry version to 0.6.0. Changed to Flink Table Planner library in Flink SQL sample.
`./gradlew clean installDist` should pass. Flink SQL sample is working.
> Issue 343: Prepare for 0.13 release
