standalone-examples/src/main/java/io/pravega/example/consolerw/ConsoleWriter.java, standalone-examples/src/main/java/io/pravega/example/gettingstarted/HelloWorldWriter.java
`AckFuture` was removed in pull request pravega/pravega#1356. This pull request corrects the references.
Fixes #42
=> Issue 42: Remove AckFuture references

anomaly-detection/build.gradle, build.gradle, flink-examples/build.gradle, gradle.properties, standalone-examples/src/main/java/io/pravega/example/consolerw/ConsoleWriter.java, standalone-examples/src/main/java/io/pravega/example/iot/TurbineHeatSensor.java, standalone-examples/src/main/java/io/pravega/example/noop/NoopReader.java, standalone-examples/src/main/java/io/pravega/example/statesynchronizer/SharedMap.java
Updated samples code to align with 
- Flink Connector
- Pravega 0.2.0-SNAPSHOT
Tested and confirmed standalone samples by following steps as mentioned in https://github.com/pravega/pravega-samples/tree/master/standalone-examples
=> [Issue 48] Updated samples to align with connectors

standalone-examples/src/main/java/io/pravega/example/consolerw/ConsoleWriter.java, standalone-examples/src/main/java/io/pravega/example/iot/TurbineHeatSensor.java, standalone-examples/src/main/java/io/pravega/example/noop/NoopReader.java, standalone-examples/src/main/java/io/pravega/example/statesynchronizer/SharedMap.java
The transaction API changes that are already pushed in master is not ported yet in release-nautilus-0.3 branch which will cause compile error.
=> [Issue-46] Updated samples to reflect Pravega txn API changes

anomaly-detection/build.gradle, gradle.properties
- Updated Pravega and Controller version to point to release version `0.2.0`
=> [Issue 52] updated pravega and connection version to 0.2.0

flink-examples/doc/flink-wordcount/README.md, flink-examples/src/main/java/io/pravega/examples/flink/wordcount/Constants.java
Co-authored-by: Kartik Vandra <kvandra@ users.noreply.github.com
fix #65
=> fix typo of DEFAULT_PORT in flink wordcount sample

standalone-examples/README.md
Signed-off-by: PrabhaVeerubhotla <vvlprabha@gmail.com>
Fixing the broken link of Pravega deployment.
=> Issue 67: Fix the broken link of instructions for running pravega in README of standalone 

flink-examples/build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, standalone-examples/src/main/java/io/pravega/example/consolerw/ConsoleReader.java, standalone-examples/src/main/java/io/pravega/example/gettingstarted/HelloWorldReader.java, standalone-examples/src/main/java/io/pravega/example/iot/TurbineHeatSensor.java, standalone-examples/src/main/java/io/pravega/example/noop/SimpleReader.java, standalone-examples/src/main/java/io/pravega/example/statesynchronizer/SharedMap.java
- updated to gradle 4.5, shadow 2.0.3
- updated to pravega/connector 0.3.0-SNAPSHOT
- updated third-party dependencies to match pravega
- updated API usage (ClientConfig)
Signed-off-by: Eron Wright <eronwright@gmail.com>
Closes #70
=> [issue-70] Create a develop branch

build.gradle, gradle.properties
This PR addresses the issue https://github.com/pravega/pravega-samples/issues/78
* updated pravega and connector snapshot artifact version
* added jfrog repository configuration to build script
=> [issue-78] Update develop branch to pull snapshot dependency from jcenter

flink-examples/src/main/java/io/pravega/examples/flink/primer/process/ExactlyOnceWriter.java, gradle.properties, standalone-examples/src/main/java/io/pravega/example/consolerw/ConsoleWriter.java, standalone-examples/src/main/java/io/pravega/example/iot/TurbineHeatSensor.java
This PR addresses the issue https://github.com/pravega/pravega-samples/issues/95
* updated pravega and connector snapshot version
* removed transaction grace period API call reference
Ran `./gradlew clean build` and verified build is successful
=> [issue-95] Remove transaction grace period API call

hadoop-examples/README.md, hadoop-examples/build.gradle, hadoop-examples/gradle.properties, hadoop-examples/src/main/java/io/pravega/examples/hadoop/ExampleDriver.java, hadoop-examples/src/main/java/io/pravega/examples/hadoop/PravegaOutputFormat.java, hadoop-examples/src/main/java/io/pravega/examples/hadoop/PravegaOutputRecordWriter.java, hadoop-examples/src/main/java/io/pravega/examples/hadoop/RandomTextWriter.java, hadoop-examples/src/main/java/io/pravega/examples/hadoop/RandomWriter.java, hadoop-examples/src/main/java/io/pravega/examples/hadoop/TextSerializer.java, hadoop-examples/src/main/java/io/pravega/examples/hadoop/WordCount.java, hadoop-examples/src/main/java/io/pravega/examples/hadoop/WordMean.java, hadoop-examples/src/main/java/io/pravega/examples/hadoop/WordMedian.java, hadoop-examples/src/main/java/io/pravega/examples/spark/WordCount.java
This PR is a cherry-pick of commit `e9022b6d1d2140f35bfac7b9d601bf205c311ef7` to branch `develop`. Please refer to this PR for further detail: #77.
=> Issue 98: Hadoop connectors examples targeting develop branch

standalone-examples/build.gradle, standalone-examples/src/main/java/io/pravega/example/consolerw/ConsoleReader.java, standalone-examples/src/main/java/io/pravega/example/streamcuts/Constants.java, standalone-examples/src/main/java/io/pravega/example/streamcuts/StreamCutsCli.java, standalone-examples/src/main/java/io/pravega/example/streamcuts/StreamCutsExample.java
This PR is a cherry-pick of commit 1b612f283a990b07b6058caf4b15e5bab2557d09 to branch `develop`. Please refer to this PR for further detail: #80.
=> Issue 100: Streamcuts sample in develop branch

flink-connector-examples/src/main/java/io/pravega/example/flink/primer/process/ExactlyOnceWriter.java, gradle.properties
This PR addresses the issue https://github.com/pravega/pravega-samples/issues/121
* updated connector snapshot version
* fixed connector writer transaction API change
=> [issue-121] Fix transaction timeout API change

pravega-client-examples/src/main/java/io/pravega/example/streamcuts/StreamCutsExample.java
Changed the way of creating stream cuts in `StreamCutsExample.java`.
Avoid intrusive access to checkpoint positions to get a stream cut at a specific event.
Now we only make use of `close()` method on the reader to persist the current reader position and get an updated value in `readerGroup.getStreamCuts()` call.
Execute the `StreamCutsCli.java` application (which internally uses `StreamCutsExample.java`). It should be working as before.
=> Issue 135: Avoid accessing checkpoint positions to get stream cuts

gradle.properties
Upgraded artifacts to version `0.3.1`.
Fixes #139.
Updates artifact versions in `gradle.properties` to `0.3.1`
=> Issue 139: Update artifacts of r0.3 to version 0.3.1.

gradle.properties
Upgrades `master` branch to reflect release version `v0.3.1`.
Fixes #141.
Updates `gradle.properties` (cherry picked commit in `r0.3`).
=> Issue 141: Update master branch to release 0.3.1

gradle.properties
Set  `samplesVersion=0.4.0-SNAPSHOT` in `develop` branch.
Fixes #145.
Updates `gradle.properties` by correctly setting `samplesVersion`.
=> Issue 145: Fixed samplesVersion in develop branch

hadoop-connector-examples/README.md, hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/wordcount/WordCount.java, pravega-client-examples/src/main/java/io/pravega/example/streamcuts/StreamCutsExample.java
Signed-off-by: Bo Yang <b.yang@emc.com>
Same change as PR #137, but the target branch is 'develop' but not 'master'.
=> Sample code of using streamcut with Hadoop connector

gradle.properties, scenarios/anomaly-detection/build.gradle
**Changes**
* Updated flink connector version that was built for Flink 1.6.0
**Reason**
- to address https://github.com/pravega/pravega-samples/issues/148
=> [issue-148] Update Flink version to 1.6.0

gradle.properties
Upgrades `master` branch to reflect release version `v0.3.2`.
Fixes #155.
Updates `gradle.properties` (cherry picked commit in `r0.3`).
=> Issue 155: Update master branch to release 0.3.2

gradle.properties
Updated `gradle.properties` of `r0.3` to set `samplesVersion=0.3.3-SNAPSHOT`.
Fixes #157.
Upgrade `samplesVersion` in `gradle.properties`.
=> Issue 157: Update samplesVersion to 0.3.3-SNAPSHOT.

README.md, hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/PravegaFixedSegmentsOutputFormat.java
* Fixed invalid variable names in PravegaFixedSegmentsOutputFormat
* Fixed readme doc changing develop branch reference
Fixes https://github.com/pravega/pravega-samples/issues/206
Fixes invalid reference in the code and readme doc
./gradlew clean build should pass
=> [issue-206] Fix invalid variable name

gradle.properties
* Updated Pravega, Connector and Samples versions to 0.5.0
Fixes https://github.com/pravega/pravega-samples/issues/203
- Changes to gradle.properties 
./gradlew clean build should pass
=> [issue-203] Prepare for 0.5 release

build.gradle, flink-connector-examples/build.gradle, gradle.properties, hadoop-connector-examples/build.gradle, pravega-client-examples/build.gradle, scenarios/anomaly-detection/build.gradle, scenarios/pravega-flink-connector-sql-samples/build.gradle, scenarios/turbine-heat-processor/build.gradle, scenarios/turbine-heat-sensor/build.gradle
=> Integrate pravega-keycloak-client

gradle.properties
Set the Pravega-related artifact versions to 0.6.0.
Fixes #221.
Updates the Pravega-related artifact versions.
Build and samples should work.
=> Issue 221: Update artifacts to 0.6 release version

build.gradle, flink-connector-examples/README.md, flink-connector-examples/build.gradle, flink-connector-examples/doc/watermark/README.md, flink-connector-examples/src/main/java/io/pravega/example/flink/watermark/Constants.java, flink-connector-examples/src/main/java/io/pravega/example/flink/watermark/EventTimeAverage.java, flink-connector-examples/src/main/java/io/pravega/example/flink/watermark/PravegaWatermarkIngestion.java, flink-connector-examples/src/main/java/io/pravega/example/flink/watermark/SensorData.java, gradle.properties, gradle/wrapper/gradle-wrapper.properties, hadoop-connector-examples/build.gradle, pravega-client-examples/build.gradle, scenarios/anomaly-detection/build.gradle, scenarios/pravega-flink-connector-sql-samples/build.gradle, scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/MaxTravellersPerDestination.java, scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/PopularDestinationQuery.java, scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/PopularTaxiVendor.java, scenarios/turbine-heat-processor/build.gradle, scenarios/turbine-heat-sensor/build.gradle
Merge new `dev` commits into `master`, so it is updated to the release version `0.6.0`.
Fixes #225.
Merge `dev` into `master`.
Branches `dev` and `master` should have identical histories of commit ids.
=> Issue 225: Merge dev (0.6.0) into master

flink-connector-examples/src/main/java/io/pravega/example/flink/streamcuts/process/DataProducer.java, flink-connector-examples/src/main/java/io/pravega/example/flink/streamcuts/process/SliceProcessor.java, gradle.properties, hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/PravegaFixedSegmentsOutputFormat.java, hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/PravegaTeraSortOutputFormat.java, pravega-client-examples/src/main/java/io/pravega/example/consolerw/ConsoleReader.java, pravega-client-examples/src/main/java/io/pravega/example/consolerw/ConsoleWriter.java, pravega-client-examples/src/main/java/io/pravega/example/gettingstarted/HelloWorldReader.java, pravega-client-examples/src/main/java/io/pravega/example/gettingstarted/HelloWorldWriter.java, pravega-client-examples/src/main/java/io/pravega/example/noop/SimpleReader.java, pravega-client-examples/src/main/java/io/pravega/example/secure/SecureReader.java, pravega-client-examples/src/main/java/io/pravega/example/secure/SecureWriter.java, pravega-client-examples/src/main/java/io/pravega/example/statesynchronizer/SharedConfig.java, pravega-client-examples/src/main/java/io/pravega/example/statesynchronizer/SharedConfigCli.java, pravega-client-examples/src/main/java/io/pravega/example/statesynchronizer/SharedMap.java, pravega-client-examples/src/main/java/io/pravega/example/streamcuts/StreamCutsExample.java, scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/AbstractHandler.java, scenarios/turbine-heat-processor/src/main/java/io/pravega/turbineheatprocessor/Utils.java, scenarios/turbine-heat-sensor/src/main/java/io/pravega/turbineheatsensor/TurbineHeatSensor.java
Removed usage of deprecated Pravega API calls from Pravega samples.
Fixes #165.
Removes old API calls from Pravega samples.
Tested all modified samples locally and they seem to work fine.
=> Issue 165: Use new Pravega Client API

flink-connector-examples/build.gradle, scenarios/anomaly-detection/build.gradle, scenarios/pravega-flink-connector-sql-samples/build.gradle, scenarios/turbine-heat-processor/build.gradle
Cherry picks issue #234 into r0.6 branch.
Fixes #235.
See #234 for details.
Build should pass and issue describe in #234 should not appear.
=> Issue 235: Cherry pick PR #234 into r0.6

gradle.properties
Upgraded artifacts and samples version to latest 0.7.
Fixes #227.
Sets the samples artifacts to 0.7.0-SNAPSHOT and upgrades the rest of dependencies to latest 0.7 snapshot.
Build must pass.
=> Issue 227: Upgraded artifacts to latest 0.7 snapshot

gradle.properties
Updated all artifact versions to 0.7.0.
Fixes #238
Updates all artifact versions to 0.7.0 in `gradle.properties`.
`./gradlew clean` build should pass
=> Issue 238: Prepare for 0.7 release

flink-connector-examples/build.gradle, flink-connector-examples/src/main/java/io/pravega/example/flink/streamcuts/process/DataProducer.java, flink-connector-examples/src/main/java/io/pravega/example/flink/streamcuts/process/SliceProcessor.java, gradle.properties, hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/PravegaFixedSegmentsOutputFormat.java, hadoop-connector-examples/src/main/java/io/pravega/example/hadoop/PravegaTeraSortOutputFormat.java, pravega-client-examples/src/main/java/io/pravega/example/consolerw/ConsoleReader.java, pravega-client-examples/src/main/java/io/pravega/example/consolerw/ConsoleWriter.java, pravega-client-examples/src/main/java/io/pravega/example/gettingstarted/HelloWorldReader.java, pravega-client-examples/src/main/java/io/pravega/example/gettingstarted/HelloWorldWriter.java, pravega-client-examples/src/main/java/io/pravega/example/noop/SimpleReader.java, pravega-client-examples/src/main/java/io/pravega/example/secure/SecureReader.java, pravega-client-examples/src/main/java/io/pravega/example/secure/SecureWriter.java, pravega-client-examples/src/main/java/io/pravega/example/statesynchronizer/SharedConfig.java, pravega-client-examples/src/main/java/io/pravega/example/statesynchronizer/SharedConfigCli.java, pravega-client-examples/src/main/java/io/pravega/example/statesynchronizer/SharedMap.java, pravega-client-examples/src/main/java/io/pravega/example/streamcuts/StreamCutsExample.java, scenarios/anomaly-detection/build.gradle, scenarios/pravega-flink-connector-sql-samples/build.gradle, scenarios/pravega-flink-connector-sql-samples/src/main/java/io/pravega/connectors/nytaxi/AbstractHandler.java, scenarios/turbine-heat-processor/build.gradle, scenarios/turbine-heat-processor/src/main/java/io/pravega/turbineheatprocessor/Utils.java, scenarios/turbine-heat-sensor/src/main/java/io/pravega/turbineheatsensor/TurbineHeatSensor.java
Merge new `dev` commits into `master`, so it is updated to the release version 0.7.0.
Fixes #240.
Merge `dev` into `master`.
Branches `dev` and `master` should have identical histories of commit ids.
=> Issue 240: Merge dev (0.7.0) into master

gradle.properties
Changed samples version to 0.8.0-SNAPSHOT.
Fixes #242.
Updates samples version.
Build should pass.
=> Issue 242: Update Samples artifact version to 0.8.0-SNAPSHOT

scenarios/anomaly-detection/build.gradle, scenarios/pravega-flink-connector-sql-samples/build.gradle, scenarios/turbine-heat-processor/build.gradle
Signed-off-by: Guangfeng Xu <Guangfeng_Xu@dell.com>
Change the dependencies of `pravega-connectors-flink` in three `build.gradle` of `build.gradle(:scenarios/)`.
Fixes #252
Update dependencies.
Follow the `README.md` and the program should work.
=> [Issue 252] Update dependencies

gradle.properties
Changed samples version to 0.10.0-SNAPSHOT.
Fixes #281.
Updates samples version.
Build should pass.
Signed-off-by: Raúl <raul.gracia@emc.com>
=> Issue 281: Update Samples artifact version to 0.10.0-SNAPSHOT

gradle.properties, spark-connector-examples/README.md, spark-connector-examples/build.gradle, spark-connector-examples/run_java_spark_app.sh, spark-connector-examples/run_spark_app.sh, spark-connector-examples/src/main/python/batch_file_to_pravega.py, spark-connector-examples/src/main/python/batch_pravega_to_console.py, spark-connector-examples/src/main/python/stream_bounded_pravega_to_console.py, spark-connector-examples/src/main/python/stream_generated_data_to_pravega.py, spark-connector-examples/src/main/python/stream_pravega_to_console.py, spark-connector-examples/src/main/python/stream_pravega_to_pravega.py, spark-connector-examples/src/main/scala/io/pravega/example/spark/StreamPravegaToConsole.scala, spark-connector-examples/src/main/scala/io/pravega/example/spark/StreamPravegaToPravega.scala
- Update PySpark example to work with Python 2
- Specify spark-connectors branch to use for examples
- Fix examples project version number
Signed-off-by: Claudio Fahey <claudio.fahey@dell.com>
=> Issue 269: Update PySpark example to work with Python 2

gradle.properties
Updated samples version to 0.10.0 and all dependency artifact versions to 0.10.1. Updated Schema Registry version to 0.3.0.
Fixes #315.
Updated samples version to 0.10.0 and all dependency artifact versions to 0.10.1. Updated Schema Registry version to 0.3.0.
`./gradlew clean installDist` should pass
Signed-off-by: Raúl <raul.gracia@emc.com>
=> Issue 315: Prepare for release 0.10

gradle.properties
Changed samples version to 0.12.0-SNAPSHOT.
Fixes #329.
Updates samples version.
Build should pass.
=> Issue 329: Update sample artifacts to 0.12-SNAPSHOT

gradle.properties
Changed samples version to 0.13.0-SNAPSHOT.
Fixes #338.
Updates samples version.
Build should pass.
=> Issue 338: Update Samples artifact version to 0.13.0-SNAPSHOT
